version: '2'
services:

  mongo:
    image: sammlerio/mongo
    container_name: user-profile-mongo
    ports:
      - "27017:27017"
    logging:
      driver: none

  rabbitmq:
    image: sammlerio/rabbitmq
    container_name: user-profile-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    logging:
      driver: none
