version: '3.3'

services:

  mongo:
    image: sammlerio/mongo
    container_name: user-profile-mongo
    ports:
      - "27017:27017"
    logging:
      driver: none


  user-profile:
    image: sammlerio/user-profile
    ports:
      - "3011:3011"
    environment:
      - PORT=3011
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - WINSTER_SUPRESS_LOGGING='true'
    depends_on:
      - mongo
