version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:4.9.1@sha256:ace1cfadc0ab4f3c9aef94cb400d052ea317a280821771d36b8a761eda74765a
      - image: mongo:3.7.9@sha256:a4fe8722970f7a10ec73820f1f43ae930724267c249a9ac12d42d3fdc2a17167
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "package.json"}}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:4.9.1@sha256:ace1cfadc0ab4f3c9aef94cb400d052ea317a280821771d36b8a761eda74765a
      - image: mongo:3.7.9@sha256:a4fe8722970f7a10ec73820f1f43ae930724267c249a9ac12d42d3fdc2a17167
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
